# Generated by Django 4.2.5 on 2023-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_mobilenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
