# Generated by Django 4.2.8 on 2023-12-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
    ]
