# Generated by Django 4.2.8 on 2023-12-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
