# Generated by Django 4.2.8 on 2023-12-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
