from django.urls import path
from .views import (
    SuperAdminDashboard,
    SuperAdminLogin,
    SuperAdminLogout,
    SuperAdminAddFunds,
    SuperAdminWithdrawFunds,
    SuperAdminWallet,
    WalletWiseSellerList,
    SellerListView,
    BuyerListView,
    ProductListView,
    SellerWiseProductListView,
    CategoryWiseProductListView,
    WalletWiseSellerListView,
    SettlementView,
    FinalSettlementView,
    BuyerDashboardView,
)

urlpatterns = [
    path(
        "superadmindashboard/",
        SuperAdminDashboard.as_view(),
        name="superadmin-dashboard",
    ),
    path(
        "superadminlogin/",
        SuperAdminLogin.as_view(),
        name="superadmin-login",
    ),
    path(
        "superadminlogout/",
        SuperAdminLogout.as_view(),
        name="superadmin-login",
    ),
    path(
        "superadminaddfund/",
        SuperAdminAddFunds.as_view(),
        name="superadmin-add-funds",
    ),
    path(
        "superadminwithdrawfund/",
        SuperAdminWithdrawFunds.as_view(),
        name="superadmin-funds-withdrawal",
    ),
    path(
        "superadminwallet/",
        SuperAdminWallet.as_view(),
        name="superadmin-wallet",
    ),
    path(
        "walletwisesellerlist/",
        WalletWiseSellerList.as_view(),
        name="walletwise-sellerlist",
    ),
    path(
        "sellerlist/",
        SellerListView.as_view(),
        name="sellerlist",
    ),
    path(
        "buyerlist/",
        BuyerListView.as_view(),
        name="buyerlist",
    ),
    path(
        "productlist/",
        ProductListView.as_view(),
        name="productlist",
    ),
    path(
        "sellerproductlist/",
        SellerWiseProductListView.as_view(),
        name="sellerproductlist",
    ),
    path(
        "categoryproductlist/",
        CategoryWiseProductListView.as_view(),
        name="categoryproductlist",
    ),
    path(
        "sellerwalletlist/",
        WalletWiseSellerListView.as_view(),
        name="sellerwalletlist",
    ),
    path(
        "settlementpage/",
        SettlementView.as_view(),
        name="settlementpage",
    ),
    path(
        "finalsettlement/",
        FinalSettlementView.as_view(),
        name="finalsettlement",
    ),
    path(
        "buyerdashboard/",
        BuyerDashboardView.as_view(),
        name="buyerdashboard",
    ),
]
