# Generated by Django 4.2.8 on 2023-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
