# Generated by Django 4.2.8 on 2023-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('superadmin', 'Superadmin')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
