# Generated by Django 4.2.8 on 2023-12-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_superadmin_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='approved',
        ),
    ]
