# Generated by Django 4.2.8 on 2023-12-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_wallet_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('superadmin', 'superadmin')], max_length=10),
        ),
    ]
