# Generated by Django 4.2.8 on 2023-12-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_superadminwallet'),
        ('superadmin', '0004_wallet'),
    ]

    operations = [
    ]
