# Generated by Django 4.2.8 on 2023-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyersbilling_cart_item_buyersbilling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitems',
            name='buyer_details',
        ),
    ]
