# Generated by Django 4.2.8 on 2023-12-13 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_product_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0002_alter_buyer_buyer_alter_buyer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('postal', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('notes', models.TextField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.cartitem')),
            ],
        ),
    ]
