# Generated by Django 4.2.8 on 2023-12-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_remove_billitems_buyer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
