# Generated by Django 4.2.8 on 2023-12-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('notes', models.TextField()),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.cartitem')),
            ],
        ),
    ]
