# Generated by Django 4.2.8 on 2023-12-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyerbilling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerbilling',
            name='cart_item',
        ),
    ]
