# Generated by Django 4.2.8 on 2023-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_buyerbilling_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerbilling',
            name='state',
        ),
    ]
