# Generated by Django 4.2.8 on 2023-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyerbilling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerbilling',
            old_name='zipcode',
            new_name='postal',
        ),
        migrations.RemoveField(
            model_name='buyerbilling',
            name='company_name',
        ),
    ]
