# Generated by Django 4.2.8 on 2023-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyer_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_type',
            field=models.CharField(default='buyer', max_length=10),
        ),
    ]
