# Generated by Django 4.2.8 on 2023-12-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_cartitem_buyerbilling'),
        ('buyer', '0006_rename_zipcode_buyerbilling_postal_and_more'),
    ]

    operations = [
    ]
