# Generated by Django 4.2.8 on 2023-12-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_alter_buyer_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.billitems')),
            ],
        ),
    ]
