# Generated by Django 4.2.8 on 2023-12-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_alter_buyerbilling_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerbilling',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='buyerbilling',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
