# Generated by Django 4.2.8 on 2023-12-13 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0008_rename_first_name_buyerbilling_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbilling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
