# Generated by Django 4.2.8 on 2023-12-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_product_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0009_alter_buyerbilling_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=0)),
                ('buyer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerbilling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
