# Generated by Django 4.2.8 on 2023-12-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_merge_20231214_1526'),
        ('buyer', '0010_billitems'),
    ]

    operations = [
    ]
